# Generated by Django 3.1.1 on 2020-09-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('data_nascimento', models.DateField()),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
