# Generated by Django 3.1.1 on 2020-09-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('resposta_avaliacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('prestador_id', models.IntegerField()),
                ('pergunta_1', models.CharField(max_length=1)),
                ('pergunta_2', models.CharField(max_length=1)),
                ('pergunta_3', models.CharField(max_length=1)),
                ('pergunta_4', models.CharField(max_length=1)),
                ('pergunta_5', models.CharField(max_length=1)),
                ('pergunta_6', models.CharField(max_length=1)),
                ('pergunta_7', models.CharField(max_length=1)),
                ('pergunta_8', models.CharField(max_length=1)),
                ('pergunta_9', models.CharField(max_length=1)),
                ('pergunta_10', models.CharField(max_length=1)),
                ('pergunta_11', models.CharField(max_length=1)),
                ('pergunta_12', models.CharField(max_length=1)),
                ('pergunta_13', models.CharField(max_length=1)),
                ('pergunta_14', models.CharField(max_length=1)),
                ('pergunta_15', models.CharField(max_length=1)),
            ],
        ),
    ]
