# Generated by Django 3.1.1 on 2020-09-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termometro', '0002_checklist_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador_id', models.IntegerField()),
                ('endereço', models.CharField(max_length=200)),
            ],
        ),
    ]
